### ISSUE TITLE
Error on Raspberry Pi with Inject Node

### ISSUE THREAD

**Issue by uli6** [Steveorevo/node-red-contrib-nbrowser#15]
Hey guys, i'm  having this error:

```
13 Jul 17:19:02 - [red] Uncaught Exception:
13 Jul 17:19:02 - Error: spawn /config/node-red/node_modules/electron/dist/electron ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hassio-addon-node-red@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"`
npm ERR! Exit status 1
```

I'm just testing the pallet so I've a Inject node wired to nbrowser node and then a debug node.

**Comment by Steveorevo** [comment]
What OS and Window manager versions are you using? I.e. is this Raspbian "Stretch" with the default web browser?

**Comment by Steveorevo** [comment]
Also, what version of NodeJS?

**Comment by Steveorevo** [comment]
See last comment in #5

You need a “window manager” or could install xvfb.
