### ISSUE TITLE
Install on Raspberry

### ISSUE THREAD

**Issue by MaxRei-dev** [Steveorevo/node-red-contrib-nbrowser#3]
hi,
i've got the following error trying to install on raspberry:
`30 Oct 14:11:47 - [warn] Installation of module node-red-contrib-nbrowser failed:
30 Oct 14:11:47 - [warn] ------------------------------------------
30 Oct 14:11:47 - [warn] Error: Command failed: npm install --save --save-prefix="~" --production node-red-contrib-nbrowser@1.0.1
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git://github.com/segmentio/nightmare.git resetting remote /home/pi/.npm/_git-remotes/git-github-com-segmentio-nightmare-git-2b27afcf because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git://github.com/rosshinkley/nightmare-download-manager.git resetting remote /home/pi/.npm/_git-remotes/git-github-com-rosshinkley-nightmare-download-manager-git-81a9c2d9 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git://github.com/rosshinkley/nightmare-upload.git resetting remote /home/pi/.npm/_git-remotes/git-github-com-rosshinkley-nightmare-upload-git-a2765c33 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git://github.com/ageitgey/node-unfluff.git resetting remote /home/pi/.npm/_git-remotes/git-github-com-ageitgey-node-unfluff-git-6ab99e5b because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:14:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:69:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:81:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:90:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror git://github.com/segmentio/nightmare.git /home/pi/.npm/_git-remotes/git-github-com-segmentio-nightmare-git-2b27afcf: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror git://github.com/segmentio/nightmare.git /home/pi/.npm/_git-remotes/git-github-com-segmentio-nightmare-git-2b27afcf: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror git://github.com/rosshinkley/nightmare-download-manager.git /home/pi/.npm/_git-remotes/git-github-com-rosshinkley-nightmare-download-manager-git-81a9c2d9: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror git://github.com/rosshinkley/nightmare-download-manager.git /home/pi/.npm/_git-remotes/git-github-com-rosshinkley-nightmare-download-manager-git-81a9c2d9: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror git://github.com/rosshinkley/nightmare-upload.git /home/pi/.npm/_git-remotes/git-github-com-rosshinkley-nightmare-upload-git-a2765c33: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror git://github.com/rosshinkley/nightmare-upload.git /home/pi/.npm/_git-remotes/git-github-com-rosshinkley-nightmare-upload-git-a2765c33: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror git://github.com/ageitgey/node-unfluff.git /home/pi/.npm/_git-remotes/git-github-com-ageitgey-node-unfluff-git-6ab99e5b: undefined
npm ERR! git clone --template=/home/pi/.npm/_git-remotes/_templates --mirror git://github.com/ageitgey/node-unfluff.git /home/pi/.npm/_git-remotes/git-github-com-ageitgey-node-unfluff-git-6ab99e5b: undefined
npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "--save-prefix=\"~\"" "--production" "node-red-contrib-nbrowser@1.0.1"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.node-red/npm-debug.log
`

**Comment by MaxRei-dev** [comment]
got it hade to install git
